### ISSUE TITLE
Face detection failure

### ISSUE THREAD

**Issue by oguchi-ebube** [TejaGollapudi/Fast-Multi-scale-Face-Detection-ConvNet#1]
Traceback (most recent call last):
  File "demo.py", line 61, in <module>
    swap_channels=swap_channels)
  File "/Users/ebubeoguchi/Soccer Dataset/Fast-Multi-scale-Face-Detection-ConvNet/models/keras_ssd512.py", line 325, in ssd_512
    conv4_3_norm = L2Normalization(gamma_init=20, name='conv4_3_norm')(conv4_3)
  File "/Users/ebubeoguchi/Soccer Dataset/Fast-Multi-scale-Face-Detection-ConvNet/keras_layers/keras_layer_L2Normalization.py", line 47, in __init__
    if K.image_dim_ordering() == 'tf':
AttributeError: module 'keras.backend' has no attribute 'image_dim_ordering'

**Comment by TejaGollapudi** [comment]
Hi Oguchi,
Which version of Keras are you using ?
I believe that this attribute works till keras 2.3.

**Comment by oguchi-ebube** [comment]
i am using  keras 2.3

**Comment by oguchi-ebube** [comment]
it is still giving the same error

**Comment by TejaGollapudi** [comment]
https://github.com/keras-team/keras/issues/12649       According to this issue, this works till keras 2.2.3.  
You could try using a lower Keras version or change the code to 

K.image_data_format() == 'tf':
